### ISSUE TITLE
finish first implementation of the legacysurvey module

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/astroquery#3]

**Comment by burnout87** [comment]
To understand:

- necessary parameters for the file to be requested during an object/tractor query
- necessary parameters for the file to be requested during a brick_list query
- necessary parameters fr the request of a region query

**Comment by burnout87** [comment]
>     * necessary parameters for the file to be requested during an object/tractor query



>     * necessary parameters for the file to be requested during a brick_list query



>     * necessary parameters fr the request of a region query

**Comment by burnout87** [comment]
Closed by mistake.

Re-opened

**Comment by burnout87** [comment]
A first implementation in the legacysurvey is now completed.

Focus will now be on the renku plugin development
