### ISSUE TITLE
maybe an issue in astroquery module?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/astroquery#9]
see https://renkulab.io/gitlab/vladimir.savchenko/oda-sdss/-/issues/2

**Comment by volodymyrss** [comment]
The problem seems identifiable: https://github.com/oda-hub/legacysurvey-backend/issues/3#issuecomment-1020204272

**Comment by volodymyrss** [comment]
is this done @dsavchenko @burnout87 ?

**Comment by volodymyrss** [comment]
is this done @dsavchenko @burnout87 ?

**Comment by burnout87** [comment]
yes!
